apiVersion: v1
kind: Service
metadata:
  annotations:
    app: gateway
    kompose.cmd: kompose convert -o kubernetes/production/kompose
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
