apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    app: gateway
    kompose.cmd: kompose convert -o kubernetes/production/kompose
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        app: gateway
        kompose.cmd: kompose convert -o kubernetes/production/kompose
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - image: lecstor-gateway:production
        name: gateway
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
