apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    NAME: rabbitmq
    kompose.cmd: kompose convert -o kubernetes/production/kompose
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        NAME: rabbitmq
        kompose.cmd: kompose convert -o kubernetes/production/kompose
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
      hostname: rabbit
      restartPolicy: Always
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq
status: {}
