apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/production/kompose
    kompose.service.type: LoadBalancer
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  ports:
  - name: "4321"
    port: 4321
    targetPort: 80
  selector:
    io.kompose.service: react-app
  type: LoadBalancer
status:
  loadBalancer: {}
