apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/production/kompose
    kompose.service.type: LoadBalancer
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/production/kompose
        kompose.service.type: LoadBalancer
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: react-app
    spec:
      containers:
      - image: lecstor-react-app:production
        name: react-app
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
