version: "3.7"
services:
  gateway:
    image: "lecstor-gateway:${TAG}"
    build:
      context: ./
      dockerfile: ./services/gateway/Dockerfile
      target: "${BUILD_TARGET}"
    depends_on:
      - postgres
      - rabbitmq
    labels:
      app: gateway
  react-app:
    image: "lecstor-react-app:${TAG}"
    build:
      context: ./
      dockerfile: ./apps/react-app/Dockerfile
      target: "${BUILD_TARGET}"
    depends_on:
      - gateway
    labels:
      kompose.service.type: LoadBalancer
  postgres:
    image: "postgres:11"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: fooBar
      POSTGRES_USER: lecstor
      POSTGRES_DB: lecstor
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    build:
      context: rabbitmq
    hostname: "rabbit"
    labels:
      NAME: "rabbitmq"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      # image: "rabbitmq:alpine"
    # hostname: "rabbit"
    # ports:
    #   - "15672:15672"
    #   - "5672:5672"
    # labels:
    #   NAME: "rabbitmq"
    # volumes:
    #   - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
volumes:
  postgres-data:
  rabbitmq:
    