version: "3.7"
services:
  base:
    image: base
    build: .
  gateway:
    image: "lecstor-gateway:${TAG}"
    build:
      context: ./
      dockerfile: ./services/gateway/Dockerfile
      target: "${BUILD_TARGET}"
    depends_on:
      - base
      - postgres
      - rabbitmq
    labels:
      app: gateway
    environment:
      - NODE_ENV
  react-app:
    image: "lecstor-react-app:${TAG}"
    build:
      context: ./
      dockerfile: ./apps/react-app/Dockerfile
      target: "${BUILD_TARGET}"
    depends_on:
      - base
      - gateway
    labels:
      kompose.service.type: LoadBalancer
    environment:
      - NODE_ENV
  postgres:
    image: "postgres:11"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: fooBar
      POSTGRES_USER: lecstor
      POSTGRES_DB: lecstor
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    build:
      context: rabbitmq
    hostname: "rabbit"
    labels:
      NAME: "rabbitmq"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
volumes:
  postgres-data:
  rabbitmq:
    